# MPPT Tempcontrol Config
# Solar chargers are discovered automatically from DBus.
# No need to list them manually.

[DEFAULT]
# Update interval in milliseconds
updateInterval = 30000

# First DBus temperature device instance number; increments by 1 for each discovered mppt charger
deviceinstancebase = 24

# First DBus temperature device instance number; increments by 1 for each discovered alternator charger
alternatorinstancebase = 26
